#!/usr/bin/env bash 

declare -a no_updated_packages
outdated_packages=$(npm outdated | tail -n +2)

function commit_bump {
    git add package.json package-lock.json && git commit -m "Bump ${1} from ${2} to ${3}"
}

function undo_changes {
    git checkout package.json package-lock.json
    npm install
}

while read package actual_version coll3 latest_version col5
do 
    echo "Try to bump ${package} from ${actual_version} to ${latest_version}"
    npm install $package@$latest_version && npm test 

    if [ $? -eq 0 ]; then
    commit_bump $package $actual_version $latest_version
    else
    no_updated_packages+=(${package})
    undo_changes
    fi
    
done <<< "$outdated_packages"

echo "No updated packages :"
for package in ${no_updated_packages[*]}
do
    printf "   %s\n" $package
done
